version: '3.1'

services:
  scorpio-db:
    image: postgres:10.4
    volumes:
      - scorpiodbvolume:/var/lib/postgresql/data/
    networks:
      - scorpio
  scorpio-web:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - scorpio
    ports:
      - "8008:8008"
    depends_on:
      - scorpio-db
  scorpio-cron:
    build: 
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - /data/logs/cron:/var/log/scorpio-cron
    networks:
      - scorpio

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8000
      - http.cors.allow-headers=Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - scorpio
    ports:
      - 9201:9201

volumes:
  scorpiodbvolume:
  elasticsearch:

networks:
  scorpio:
