# Generated by Django 2.2.13 on 2020-06-15 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(0, 'Started'), (1, 'Finished'), (2, 'Errored')], max_length=100)),
                ('object_type', models.CharField(choices=[('agent', 'Agent'), ('collection', 'Collection'), ('object', 'Object'), ('term', 'Term')], max_length=100)),
                ('object_status', models.CharField(choices=[('indexed', 'Indexed'), ('deleted', 'Deleted')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndexRunError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexer.IndexRun')),
            ],
            options={
                'ordering': ('datetime',),
            },
        ),
    ]
