# Generated by Django 2.2.13 on 2020-07-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_indexrun_indexrunerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexrun',
            name='object_type',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('collection', 'Collection'), ('object', 'Object'), ('term', 'Term')], max_length=100, null=True),
        ),
    ]
