# Generated by Django 2.2.7 on 2020-01-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_dataobject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataobject',
            old_name='type',
            new_name='object_type',
        ),
    ]
